README.md
Added content to Read me including brief intro, quickstart, install, contributing guide, and License
=> [Update] Added baseline information to readme

README.md
Changes are limited to only Readme.md
=> [Minor] Merge Dev & Master

README.md, contributor.md
Three changes:
README.md:
1) Added npm install *--save* to the install instructions
2) Corrected the link to the API documentation
contributor.md:
3) Corrected the link to the Azure central contributors page (link was malformed)
=> Fixed up the README.md and a bad link in contributor.md

README.md, contributor.md
The README.md referenced the GitHub repository - changed to reference the NPM package.
=> Updated README for npm publication

jsdoc/configuration.types.js, jsdoc/tables.js, src/data/sql/index.js, src/express/middleware/parseQuery.js, src/express/tables/index.js, src/index.js, test/express/integration/tables.behavior.tests.js
Defaults to 1000 to match mobile services behavior
=> Request size limit

README.md, contributor.md
Added organization paragraph into the README.  Also removed reference to dev branch from Contributor.md file.  FInally, added a "Contact Us" section to README as it was referenced from the Contributor.md file.
=> Updated README and Contributor for GitHub Organization

samples/todo/app.js, samples/todo/azureMobile.js, samples/todo/package.json, samples/todo/tables/TodoItem.js
New sample is updated to the latest API and has comments.
=> Updated canonical tables sample 'samples\todo'

samples/authentication/.gitignore, samples/basic-app/.gitignore, samples/customApi/.gitignore, samples/dynamic-schema/.gitignore, samples/personal-table/.gitignore, samples/readonly-table/.gitignore, samples/seeding-data/.gitignore, samples/static-schema/.gitignore, samples/todo/.gitignore
Ignore azureMobile.js explicitly in the gitignore files in samples directory
=> (#158) Fix for samples gitignore

src/data/sql/dynamicSchema.js, src/data/sql/errorCodes.js, src/data/sql/execute.js, src/data/sql/schema.js, src/data/sql/statements/updateSchema.js, test/data/sql/integration.schema.tests.js
I would have done a codeflow, but some credentials issue from home PC.
=> Fixed schema.initialize failing when no changes required

test/auth/auth.tests.js
This is to update the token checking for the non-gateway syntax
=> Updated unit tests for correct EasyAuth syntax

src/express/middleware/eTag.js, src/express/middleware/nextLink.js, src/express/middleware/parseItem.js, src/express/middleware/parseQuery.js, src/express/middleware/renderResults.js, src/express/tables/index.js, src/express/tables/tableRouter.js, src/index.js, src/utilities/strings.js, test/express/integration/tables.behavior.tests.js, test/express/integration/tables.data.tests.js, test/express/integration/tables.etag.tests.js, test/express/integration/tables.link.tests.js, test/express/middleware/eTag.tests.js, test/express/middleware/nextLink.tests.js, test/express/tables/table.tests.js, test/express/tables/tableRouter.tests.js, test/utilities/strings.tests.js
=> ETag and nextLink middleware

src/auth/getIdentity.js
This version of the getIdentity() call does not do any post-processing of the response from the server.
Fixes #173.
=> Working getIdentity() call

src/auth/getIdentity.js, src/auth/normalizeClaims.js, test/auth/normalizeClaims.tests.js
=> (#184) Normalize claims

src/auth/normalizeClaims.js
string.startsWith is an ES6 method.  Changed to string.indexOf() usage to support Node versions prior to v4.2
=> Changed startsWith (ES6) to indexOf (ES5.1)

README.md
=> (#199) Added Gitter

.travis.yml, README.md, test/data/sql/integration.concurrency.tests.js, test/data/sql/integration.softDelete.tests.js, test/express/endtoend/tables.tests.js, test/express/integration/tables.concurrency.tests.js, test/express/integration/tables.creation.tests.js, test/express/integration/tables.data.tests.js, test/express/integration/tables.dynamicSchema.tests.js, test/express/integration/tables.initialize.tests.js, test/express/integration/tables.softDelete.tests.js, test/express/integration/version.tests.js
mocha -g sql.integration --invert will run all tests without sql dependency
=> Travis-CI test changes

src/express/middleware/createContext.js
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/209
=> Add configuration to context

jsdoc/context.js, src/express/middleware/createContext.js, test/express/integration/tables.behavior.tests.js
=> Added logger to context

src/index.js, src/utilities/promises.js, test/configuration/configuration.tests.js
=> Consume promiseConstructor

src/express/tables/table.js
=> Improved table operation jsdoc

samples/authentication/app.js, samples/authentication/package.json, samples/authentication/tables/TodoItem.js, samples/basic-app/app.js, samples/basic-app/package.json, samples/customApi/package.json, samples/dynamic-schema/app.js, samples/dynamic-schema/package.json, samples/personal-table/app.js, samples/personal-table/package.json, samples/personal-table/tables/TodoItem.js, samples/push-on-insert/app.js, samples/push-on-insert/package.json, samples/readonly-table/app.js, samples/readonly-table/package.json, samples/readonly-table/tables/TodoItem.js, samples/seeding-data/app.js, samples/seeding-data/package.json, samples/seeding-data/tables/TodoItem.js, samples/static-schema/app.js, samples/static-schema/package.json, samples/static-schema/tables/TodoItem.js, samples/todo/app.js, samples/todo/azureMobile.js, samples/todo/package.json, samples/todo/tables/TodoItem.js
=> Adjusted spacing to conform to standards

e2etest/api/applicationPermission.js, e2etest/server.js, e2etest/tables/authenticated.js
some tests passing are still dependent upon fixing #258
=> Android e2e login changes

samples/authentication/package.json, samples/basic-app/package.json, samples/customApi/package.json, samples/dynamic-schema/package.json, samples/personal-table/package.json, samples/push-on-insert/package.json, samples/readonly-table/package.json, samples/seeding-data/package.json, samples/static-schema/package.json, samples/todo/azureMobile.js, samples/todo/package.json
=> Update samples to beta1

src/data/index.js, src/data/mssql/dynamicSchema.js, src/data/mssql/index.js, src/data/mssql/schema.js, src/data/mssql/statements/delete.js, test/data/sql/integration.dynamicSchema.tests.js, test/data/sql/integration.tests.js, test/data/sql/statements.tests.js
=> Delete / Soft Delete fix

src/data/mssql/helpers.js, src/data/mssql/statements/createTrigger.js, test/data/sql/statements.tests.js
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/226
=> Changed DATETIMEOFFSET(3) to (7)

src/data/mssql/index.js, src/express/index.js
This simplifies logging of configuration and also resolves https://github.com/Azure/azure-mobile-apps-node/issues/167.
This may not be the best solution - the winston configuration is somewhat verbose.
@mamaso @adrianhall
=> Changed configuration logging

src/configuration/loader.js, test/configuration/files/tables/readme.md, test/configuration/loader.tests.js
Loading a directory with files other than .js or .json would fail on the unsupported files.
=> Fixed loader issue with unsupported file types

src/index.js
=> Fixed global configuration issue

jsdoc/configuration.types.js, src/cors/index.js, src/express/index.js, src/express/middleware/exposeHeaders.js, src/index.js, test/express/integration/cors.tests.js, typings/azure-mobile-apps/azure-mobile-apps.d.ts
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/323
=> Added exposeHeaders middleware and config option

jsdoc/configuration.types.js, src/configuration/fromEnvironment.js, src/cors/index.js, src/index.js, test/cors/cors.headers.tests.js, test/cors/cors.origin.tests.js, test/express/integration/cors.tests.js, test/express/middleware/crossOrigin.tests.js, typings/azure-mobile-apps/azure-mobile-apps.d.ts
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/288
=> Renamed origins to hostnames

src/express/middleware/renderResults.js, test/express/endtoend/tables.tests.js, test/express/integration/middleware.tests.js, test/express/integration/tables/behavior.tests.js, test/express/integration/tables/concurrency.tests.js, test/express/integration/tables/data.tests.js, test/express/integration/tables/dynamicSchema.tests.js, test/express/integration/tables/etag.tests.js, test/express/integration/tables/filters.tests.js, test/express/integration/tables/initialize.tests.js, test/express/integration/tables/link.tests.js, test/express/integration/tables/softDelete.tests.js
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/305
=> POST operations return 201 on success

src/configuration/importDefinition.js
Altered importDefinition() method so that it supports the ES2015 Module Syntax.
=> ES2015 support

samples/personal-table/tables/TodoItem.js, samples/todo/tables/TodoItem.js
Fixes #228 - can be closed when merged.
=> #228 Updated samples for update/delete modifications

src/configuration/defaults.js, src/configuration/from/commandLine.js, src/utilities/environment.js
=> Fix basePath and q issue

src/auth/normalizeClaims.js, test/auth/normalizeClaims.tests.js
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/340
=> normalizeClaims handles single objects

.gitignore, .travis.yml, package.json, test/mocha.opts
=> Added linting to travis build

samples/getidentity/README.md, samples/getidentity/app.js, samples/getidentity/package.json, samples/getidentity/tables/TodoItem.js
A sample that includes getIdentity() usage.
=> getIdentity() example

src/express/middleware/swagger.js, src/swagger/index.js, src/swagger/tableOperation.js, src/swagger/tablePaths.js, test/swagger/swagger.tests.js
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/351
=> Added operationId and schemes to swagger definition

src/data/mssql/index.js, src/express/middleware/parseItem.js
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/372
=> Moved assigning ID from middleware to data layer

src/configuration/importDefinition.js, src/express/tables/tableRouter.js, test/configuration/importDefinition.tests.js, test/express/integration/auth.tests.js
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/376
=> Apply access property to table object

e2etest/tables/authenticated.js
- Change is just to be at parity with the .NET test code
=> JSON.Stringify identity value in the auth test

e2etest/movieData.js, e2etest/server.js
- Generate movie data IDs consistent with the .NET implementation
- Enable dynamicSchema for IntIdRoundTripTable
=> Minor fixes to the node e2e test code

src/auth/normalizeClaims.js, test/auth/normalizeClaims.tests.js
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/393
=> Handle multiple claims with same type

README.md
Adds dependency badges for both prod and dev dependencies in README.
fix for #301
=> (#301) Add dependencies badge

src/data/mssql/helpers.js, src/data/mssql/index.js, src/data/mssql/statements/createIndex.js, src/data/mssql/statements/createTable.js, src/data/mssql/statements/createTrigger.js, src/data/mssql/statements/delete.js, src/data/mssql/statements/getIndexes.js, src/data/mssql/statements/insert.js, src/data/mssql/statements/undelete.js, src/data/mssql/statements/update.js, src/data/mssql/statements/updateSchema.js, src/data/sqlite/helpers.js, src/data/sqlite/index.js, src/data/sqlite/statements/createIndex.js, src/data/sqlite/statements/createTable.js, src/data/sqlite/statements/createTrigger.js, src/data/sqlite/statements/delete.js, src/data/sqlite/statements/insert.js, src/data/sqlite/statements/truncate.js, src/data/sqlite/statements/undelete.js, src/data/sqlite/statements/update.js, src/data/sqlite/statements/updateSchema.js, src/express/middleware/createQuery.js, src/express/middleware/parseQuery.js, src/express/tables/index.js, test/data/integration/initialize.tests.js, test/data/integration/integration.tests.js, test/data/mssql/integration.dynamicSchema.tests.js, test/express/tables/tables.tests.js, test/swagger/swagger.tests.js
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/413
=> table.name and .databaseTableName are now distinct

src/auth/index.js, src/data/sqlite/index.js, test/auth/auth.tests.js
=> Handle non-hex encoded signing keys

src/configuration/from/file.js, src/configuration/from/settingsJson.js, src/logger.js
@mamaso for info. No impact to tests.
=> Configure console as default logger. Log config load errors

src/data/mssql/schema.js, src/data/sqlite/schema.js, test/data/integration/initialize.tests.js
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/449
@adrianhall
=> Attach ID to seeded data if not present

src/express/middleware/swagger-ui.js
@brettsam @paulbatum For info, the fix I am applying
=> Fix swagger vulnerability

jsdoc/configuration.data.js, jsdoc/configuration.types.js
@adrianhall I've added some simple documentation around configuring a custom data provider. I don't see much value in putting much more effort into this, it will be rare that customers will want to do this, we can give them more direct assistance in those cases.
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/467
=> Added custom data provider docs

package.json
=> Force sequential running of lint & test

src/data/mssql/statements/read.js, test/data/integration/query.tests.js
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/481
=> Remove ROW_NUMBER property on paged reads

src/data/mssql/statements/read.js, test/data/integration/query.tests.js
@mikejohanson Changed logic and added test
=> Fixed logic when skip = 0

src/data/index.js, src/data/wrapProvider.js, test/data/integration/query.tests.js
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/460
=> Added find method, tests and jsdoc

src/data/wrapProvider.js, src/query/index.js, test/data/integration/integration.tests.js
Resolves https://github.com/Azure/azure-mobile-apps-node/issues/485
=> Allow passing object queries or predicates to data functions

README.md
Provided direct link to Visual Studio Azure .NET SDK and Tools
=> Added Azure .NET SDK link in README

.vscode/launch.json, src/data/mssql/helpers.js, src/data/mssql/statements/createTable.js, src/data/mssql/statements/updateSchema.js, src/data/sqlite/columns/combine.js, src/data/sqlite/helpers.js, src/data/sqlite/statements/createTable.js, test/data/mssql/integration.dynamicSchema.tests.js, test/data/mssql/statements/createTable.tests.js, test/data/mssql/statements/updateSchema.tests.js, test/data/sqlite/columns/combine.tests.js, test/express/integration/swagger.tests.js, test/express/integration/tables/data.tests.js
Also added vscode mocha configuration. Integrated debugging!
=> Only create deleted column in dynamic schema if softDelete is specified

src/express/middleware/tables/nextLink.js, src/express/middleware/tables/parseQuery.js, test/express/integration/tables/link.tests.js
This makes paging behavior correct according to documentation. See https://github.com/Azure/azure-mobile-apps-node/issues/480 for more info.
=> pageSize option only has effect if top is not specified

src/express/api/index.js, test/express/integration/auth.tests.js
=> Prevent unauthenticated access to authenticated custom APIs

src/express/api/index.js, src/utilities/types.js, test/express/files/api/asyncapi.js, test/express/integration/customapi.tests.js
=> Add support for async functions in custom APIs

.travis.yml, package.json, samples/es2015/package.json, src/express/middleware/swagger-ui.js
=> Fix security issues
